name: base
channels:
  - conda-forge
  - bioconda
  - pytorch
platforms:
  - linux-64
  - osx-64
  - osx-arm64
dependencies:
  - python=3.10
  - pandas=2.1.*
  - beartype=0.11
  - black=23.9.*
  - loguru=0.7.*
  - numpy=1.26
  - mlflow=2.7.*
  - pytorch-lightning=2.1.*
  - ruff=0.1.*
  - scikit-learn=1.3.*
  - scipy
  - hydra-core=1.3.2
  - isort=5.12.*
  - pip:
    - hydra-zen==0.11.*
    - torch==2.1.*

