data_dir: /mnt/c/Users/behza/Documents/code/data/fpl_ml

# Directory where we want to write prepared data
processed_data_dir: ${data_dir}/demo_data/
mlruns_dir: ${data_dir}/mlruns/

defaults:
  - _self_
  - train: demo
