_target_: fpl_ml_projects.fpl_ml.project_train.train_torch_tpe
user_mlruns_dir: ${mlruns_dir}
train_val_data_path: ${processed_data_dir}train_val_data.csv
test_data_path: ${processed_data_dir}test_data.csv